src/objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Checkbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Text_field__c</fullName>
        <label>Text field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RerenderRendered_controller.cls
public with sharing class RerenderRendered_controller{
    public Vehicle__c vehicle ;
    public RerenderRendered_controller(ApexPages.StandardController stdController){
        Id recordId = ApexPages.CurrentPage().getParameters().get('Id') ;
        system.debug('recordId : ' + recordId ) ;
        vehicle = [Select Id, Checkbox__c, Text_field__c from Vehicle__c where Id =: recordId] ;
        system.debug('vehicle : ' + vehicle ) ;
    }
    
    public Boolean showTextField {
        get{
            return vehicle.Checkbox__c ;
        }
    }
}